-- Greenfinger 2.0 schema for oracle.
--
-- Generated by SchemaScriptsTest from the entities; do not edit by hand -- run the
-- test instead, or the next run will overwrite whatever was typed here.
--
-- Dialect: org.hibernate.dialect.OracleDialect
--
-- Run this once against an empty database, then start the nodes with
-- GF_DB_DDL=validate so that Hibernate checks the schema rather than changing it.
-- The default, update, only ever adds: a column whose type changed is left alone,
-- a dropped one stays, and two nodes starting together race to create the same
-- table.

create table crawler_catalog (
        id varchar2(36 char) not null,
        cat varchar2(45 char) not null,
        counting_type number(10,0),
        created_at timestamp(9),
        depth number(10,0),
        downstream_content varchar2(20 char),
        duration number(19,0),
        excluded_path_pattern varchar2(2000 char),
        extractor varchar2(45 char),
        fetch_interval number(19,0),
        image_enabled number(1,0) check ((image_enabled in (0,1))),
        index_version number(10,0) not null,
        last_indexed timestamp(9),
        max_fetch_size number(10,0),
        max_retry_count number(10,0),
        max_versions number(10,0) not null,
        name varchar2(255 char) not null,
        output_types varchar2(100 char) not null,
        page_encoding varchar2(45 char),
        path_pattern varchar2(2000 char) not null,
        running_state varchar2(45 char),
        search_version number(10,0) not null,
        sitemap_url varchar2(1000 char),
        start_url varchar2(1000 char),
        updated_at timestamp(9),
        url varchar2(255 char) not null,
        url_path_acceptor varchar2(2000 char),
        url_path_filter varchar2(45 char),
        primary key (id),
        constraint uk_catalog_name unique (name)
    );

    create table crawler_image (
        id varchar2(36 char) not null,
        bytes number(19,0),
        catalog_id varchar2(36 char) not null,
        content_hash varchar2(64 char) not null,
        content_type varchar2(100 char),
        created_at timestamp(9),
        first_source_url varchar2(1000 char),
        height number(10,0),
        image_file_path varchar2(1000 char) not null,
        updated_at timestamp(9),
        version number(10,0) not null,
        width number(10,0),
        primary key (id),
        constraint uk_image unique (catalog_id, version, content_hash)
    );

    create table crawler_report (
        id varchar2(36 char) not null,
        catalog_id varchar2(36 char) not null,
        content clob not null,
        created_at timestamp(9) not null,
        updated_at timestamp(9) not null,
        version number(10,0) not null,
        primary key (id),
        constraint uk_report_catalog_version unique (catalog_id, version)
    );

    create table crawler_resource (
        id varchar2(36 char) not null,
        cat varchar2(45 char) not null,
        catalog_id varchar2(36 char) not null,
        content_hash varchar2(64 char),
        created_at timestamp(9),
        depth number(10,0),
        etag varchar2(200 char),
        html_content_file_path varchar2(1000 char),
        html_file_path varchar2(1000 char),
        http_last_modified varchar2(100 char),
        link_count number(10,0),
        link_text_length number(10,0),
        referer varchar2(1000 char),
        text_length number(10,0),
        title varchar2(1000 char),
        updated_at timestamp(9),
        url varchar2(1000 char) not null,
        url_hash varchar2(64 char) not null,
        version number(10,0) not null,
        primary key (id),
        constraint uk_resource unique (catalog_id, version, url_hash)
    );

    create table crawler_resource_image (
        id varchar2(36 char) not null,
        alt_text varchar2(1000 char),
        catalog_id varchar2(36 char) not null,
        context_text varchar2(2000 char),
        created_at timestamp(9),
        image_id varchar2(36 char) not null,
        resource_id varchar2(36 char) not null,
        source_url varchar2(1000 char) not null,
        title_text varchar2(1000 char),
        updated_at timestamp(9),
        version number(10,0) not null,
        primary key (id),
        constraint uk_resource_image unique (resource_id, image_id)
    );

    create index idx_catalog_running_state 
       on crawler_catalog (running_state);

    create index idx_catalog_cat 
       on crawler_catalog (cat);

    create index idx_image_catalog_ver 
       on crawler_image (catalog_id, version);

    create index idx_report_catalog 
       on crawler_report (catalog_id);

    create index idx_resource_catalog_ver 
       on crawler_resource (catalog_id, version);

    create index idx_resource_created_at 
       on crawler_resource (catalog_id, version, created_at);

    create index idx_ri_catalog_ver 
       on crawler_resource_image (catalog_id, version);

    create index idx_ri_resource 
       on crawler_resource_image (resource_id);

    create index idx_ri_image 
       on crawler_resource_image (image_id);
