-- Greenfinger 2.0 schema for sqlserver.
--
-- Generated by SchemaScriptsTest from the entities; do not edit by hand -- run the
-- test instead, or the next run will overwrite whatever was typed here.
--
-- Dialect: org.hibernate.dialect.SQLServerDialect
--
-- Run this once against an empty database, then start the nodes with
-- GF_DB_DDL=validate so that Hibernate checks the schema rather than changing it.
-- The default, update, only ever adds: a column whose type changed is left alone,
-- a dropped one stays, and two nodes starting together race to create the same
-- table.

create table crawler_catalog (
        id varchar(36) not null,
        cat varchar(45) not null,
        counting_type int,
        created_at datetime2(7),
        depth int,
        downstream_content varchar(20),
        duration bigint,
        excluded_path_pattern varchar(2000),
        extractor varchar(45),
        fetch_interval bigint,
        image_enabled bit,
        index_version int not null,
        last_indexed datetime2(7),
        max_fetch_size int,
        max_retry_count int,
        max_versions int not null,
        name varchar(255) not null,
        output_types varchar(100) not null,
        page_encoding varchar(45),
        path_pattern varchar(2000) not null,
        running_state varchar(45),
        search_version int not null,
        sitemap_url varchar(1000),
        start_url varchar(1000),
        updated_at datetime2(7),
        url varchar(255) not null,
        url_path_acceptor varchar(2000),
        url_path_filter varchar(45),
        primary key (id)
    );

    create table crawler_image (
        id varchar(36) not null,
        bytes bigint,
        catalog_id varchar(36) not null,
        content_hash varchar(64) not null,
        content_type varchar(100),
        created_at datetime2(7),
        first_source_url varchar(1000),
        height int,
        image_file_path varchar(1000) not null,
        updated_at datetime2(7),
        version int not null,
        width int,
        primary key (id)
    );

    create table crawler_report (
        id varchar(36) not null,
        catalog_id varchar(36) not null,
        content varchar(max) not null,
        created_at datetime2(7) not null,
        updated_at datetime2(7) not null,
        version int not null,
        primary key (id)
    );

    create table crawler_resource (
        id varchar(36) not null,
        cat varchar(45) not null,
        catalog_id varchar(36) not null,
        content_hash varchar(64),
        created_at datetime2(7),
        depth int,
        etag varchar(200),
        html_content_file_path varchar(1000),
        html_file_path varchar(1000),
        http_last_modified varchar(100),
        link_count int,
        link_text_length int,
        referer varchar(1000),
        text_length int,
        title varchar(1000),
        updated_at datetime2(7),
        url varchar(1000) not null,
        url_hash varchar(64) not null,
        version int not null,
        primary key (id)
    );

    create table crawler_resource_image (
        id varchar(36) not null,
        alt_text varchar(1000),
        catalog_id varchar(36) not null,
        context_text varchar(2000),
        created_at datetime2(7),
        image_id varchar(36) not null,
        resource_id varchar(36) not null,
        source_url varchar(1000) not null,
        title_text varchar(1000),
        updated_at datetime2(7),
        version int not null,
        primary key (id)
    );

    create index idx_catalog_running_state 
       on crawler_catalog (running_state);

    create index idx_catalog_cat 
       on crawler_catalog (cat);

    alter table crawler_catalog 
       add constraint uk_catalog_name unique (name);

    create index idx_image_catalog_ver 
       on crawler_image (catalog_id, version);

    alter table crawler_image 
       add constraint uk_image unique (catalog_id, version, content_hash);

    create index idx_report_catalog 
       on crawler_report (catalog_id);

    alter table crawler_report 
       add constraint uk_report_catalog_version unique (catalog_id, version);

    create index idx_resource_catalog_ver 
       on crawler_resource (catalog_id, version);

    create index idx_resource_created_at 
       on crawler_resource (catalog_id, version, created_at);

    alter table crawler_resource 
       add constraint uk_resource unique (catalog_id, version, url_hash);

    create index idx_ri_catalog_ver 
       on crawler_resource_image (catalog_id, version);

    create index idx_ri_resource 
       on crawler_resource_image (resource_id);

    create index idx_ri_image 
       on crawler_resource_image (image_id);

    alter table crawler_resource_image 
       add constraint uk_resource_image unique (resource_id, image_id);
