-- Greenfinger 2.0 schema for h2.
--
-- Generated by SchemaScriptsTest from the entities; do not edit by hand -- run the
-- test instead, or the next run will overwrite whatever was typed here.
--
-- Dialect: org.hibernate.dialect.H2Dialect
--
-- Run this once against an empty database, then start the nodes with
-- GF_DB_DDL=validate so that Hibernate checks the schema rather than changing it.
-- The default, update, only ever adds: a column whose type changed is left alone,
-- a dropped one stays, and two nodes starting together race to create the same
-- table.

create table crawler_catalog (
        id varchar(36) not null,
        cat varchar(45) not null,
        counting_type integer,
        created_at timestamp(6),
        depth integer,
        downstream_content varchar(20),
        duration bigint,
        excluded_path_pattern varchar(2000),
        extractor varchar(45),
        fetch_interval bigint,
        image_enabled boolean,
        index_version integer not null,
        last_indexed timestamp(6),
        max_fetch_size integer,
        max_retry_count integer,
        max_versions integer not null,
        name varchar(255) not null,
        output_types varchar(100) not null,
        page_encoding varchar(45),
        path_pattern varchar(2000) not null,
        running_state varchar(45),
        search_version integer not null,
        sitemap_url varchar(1000),
        start_url varchar(1000),
        updated_at timestamp(6),
        url varchar(255) not null,
        url_path_acceptor varchar(2000),
        url_path_filter varchar(45),
        primary key (id),
        constraint uk_catalog_name unique (name)
    );

    create table crawler_image (
        id varchar(36) not null,
        bytes bigint,
        catalog_id varchar(36) not null,
        content_hash varchar(64) not null,
        content_type varchar(100),
        created_at timestamp(6),
        first_source_url varchar(1000),
        height integer,
        image_file_path varchar(1000) not null,
        updated_at timestamp(6),
        version integer not null,
        width integer,
        primary key (id),
        constraint uk_image unique (catalog_id, version, content_hash)
    );

    create table crawler_report (
        id varchar(36) not null,
        catalog_id varchar(36) not null,
        content clob not null,
        created_at timestamp(6) not null,
        updated_at timestamp(6) not null,
        version integer not null,
        primary key (id),
        constraint uk_report_catalog_version unique (catalog_id, version)
    );

    create table crawler_resource (
        id varchar(36) not null,
        cat varchar(45) not null,
        catalog_id varchar(36) not null,
        content_hash varchar(64),
        created_at timestamp(6),
        depth integer,
        etag varchar(200),
        html_content_file_path varchar(1000),
        html_file_path varchar(1000),
        http_last_modified varchar(100),
        link_count integer,
        link_text_length integer,
        referer varchar(1000),
        text_length integer,
        title varchar(1000),
        updated_at timestamp(6),
        url varchar(1000) not null,
        url_hash varchar(64) not null,
        version integer not null,
        primary key (id),
        constraint uk_resource unique (catalog_id, version, url_hash)
    );

    create table crawler_resource_image (
        id varchar(36) not null,
        alt_text varchar(1000),
        catalog_id varchar(36) not null,
        context_text varchar(2000),
        created_at timestamp(6),
        image_id varchar(36) not null,
        resource_id varchar(36) not null,
        source_url varchar(1000) not null,
        title_text varchar(1000),
        updated_at timestamp(6),
        version integer not null,
        primary key (id),
        constraint uk_resource_image unique (resource_id, image_id)
    );

    create index idx_catalog_running_state 
       on crawler_catalog (running_state);

    create index idx_catalog_cat 
       on crawler_catalog (cat);

    create index idx_image_catalog_ver 
       on crawler_image (catalog_id, version);

    create index idx_report_catalog 
       on crawler_report (catalog_id);

    create index idx_resource_catalog_ver 
       on crawler_resource (catalog_id, version);

    create index idx_resource_created_at 
       on crawler_resource (catalog_id, version, created_at);

    create index idx_ri_catalog_ver 
       on crawler_resource_image (catalog_id, version);

    create index idx_ri_resource 
       on crawler_resource_image (resource_id);

    create index idx_ri_image 
       on crawler_resource_image (image_id);
