application.title: Greenfinger UI
application.version: 1.0.0-SNAPSHOT

server:
  port: 6120
  credentials:
    user: admin
    password: admin123
spring:
  main:
    banner-mode: console
  application:
    name: greenfinger-ui-service
  profiles:
    active: local
  scheduler:
    run-mode: variable
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  redis:
    lettuce:
      pool:
        max-active: 20
        max-idle: 2
        min-idle: 1
        max-wait: 10000
  datasource:
    hikari:
      connection-timeout: 2000
      minimum-idle: 2
      maximum-pool-size: 20
      idle-timeout: 200000
      auto-commit: true
      max-lifetime: 1800000
      connection-test-query: select 1
    
doodler:
  cloud:
    sibling:
      quick-start: false 
    
management:
  security:
    enabled: false
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: '*'
      base-path: /monitor
  jmx:
    exposure:
      include: '*'
  metrics:
    tags:
      application: '${spring.application.name}'
