/*
 * Copyright 2017-2026 Fred Feng (paganini.fy@gmail.com)
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *  http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.github.greenfinger.core.schema;

import static org.assertj.core.api.Assertions.assertThat;
import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.EnumSet;
import java.util.List;
import java.util.Map;
import org.hibernate.boot.MetadataSources;
import org.hibernate.boot.registry.StandardServiceRegistry;
import org.hibernate.boot.registry.StandardServiceRegistryBuilder;
import org.hibernate.cfg.AvailableSettings;
import org.hibernate.tool.schema.TargetType;
import org.hibernate.tool.schema.internal.SchemaCreatorImpl;
import org.hibernate.tool.schema.internal.exec.ScriptTargetOutputToFile;
import org.hibernate.tool.schema.spi.ScriptTargetOutput;
import org.hibernate.tool.schema.spi.TargetDescriptor;
import org.hibernate.tool.schema.spi.ContributableMatcher;
import org.hibernate.tool.schema.spi.ExceptionHandler;
import org.hibernate.tool.schema.spi.ExecutionOptions;
import org.hibernate.tool.schema.spi.SchemaFilter;
import org.hibernate.tool.schema.spi.SourceDescriptor;
import org.hibernate.tool.schema.SourceType;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.params.ParameterizedTest;
import org.junit.jupiter.params.provider.MethodSource;
import com.github.greenfinger.core.model.Catalog;
import com.github.greenfinger.core.model.CrawlerReport;
import com.github.greenfinger.core.model.Image;
import com.github.greenfinger.core.model.Resource;
import com.github.greenfinger.core.model.ResourceImage;

/**
 * The schema, written out for every database the project is tested against.
 *
 * <p>
 * The scripts under {@code backend/sql/} are generated by this, not typed: a hand-written DDL and
 * the entities it is supposed to describe drift apart quietly, and the first anyone hears of it is
 * a column that exists on one deployment and not another. Running the test rewrites them, so a
 * change to an entity that nobody carried into the scripts shows up as a modified file.
 *
 * <p>
 * They exist because {@code ddl-auto=update} is the wrong thing to hand a production database. It
 * only ever adds: a column whose type changed is left as it was, a column that was dropped stays,
 * and two nodes starting together race each other to create the same table. What a deployment
 * wants is to run a script it has read, and then have Hibernate check rather than change --
 * {@code GF_DB_DDL=validate}.
 * 
 * @Description: SchemaScriptsTest
 * @Author: Fred Feng
 * @Date: 04/09/2026
 * @Version 2.0.0
 */
class SchemaScriptsTest {

    /** Where the generated scripts live, relative to this module. */
    private static final Path OUTPUT = Paths.get("..", "..", "docs", "sql");

    private static final List<Class<?>> ENTITIES =
            List.of(Catalog.class, Resource.class, Image.class, ResourceImage.class,
                    CrawlerReport.class);

    static List<String[]> databases() {
        return List.of(
                new String[] {"h2", "org.hibernate.dialect.H2Dialect"},
                new String[] {"sqlite", "org.hibernate.community.dialect.SQLiteDialect"},
                new String[] {"mysql", "org.hibernate.dialect.MySQLDialect"},
                new String[] {"postgresql", "org.hibernate.dialect.PostgreSQLDialect"},
                new String[] {"sqlserver", "org.hibernate.dialect.SQLServerDialect"},
                new String[] {"oracle", "org.hibernate.dialect.OracleDialect"});
    }

    @ParameterizedTest(name = "{0}")
    @MethodSource("databases")
    @DisplayName("the schema is written out for each database, and holds all five tables")
    void writesTheSchema(String name, String dialect) throws IOException {
        Files.createDirectories(OUTPUT);
        Path file = OUTPUT.resolve("schema-" + name + ".sql");
        Files.deleteIfExists(file);

        StandardServiceRegistry registry = new StandardServiceRegistryBuilder()
                .applySettings(Map.of(AvailableSettings.DIALECT, dialect,
                        // no database is opened: the dialect above is the whole of what this
                        // needs to know, and asking a driver would tie generating a script for
                        // Oracle to having an Oracle to ask
                        AvailableSettings.ALLOW_METADATA_ON_BOOT, "false",
                        AvailableSettings.FORMAT_SQL, "true"))
                .build();
        try {
            MetadataSources sources = new MetadataSources(registry);
            ENTITIES.forEach(sources::addAnnotatedClass);
            new SchemaCreatorImpl(registry, SchemaFilter.ALL).doCreation(sources.buildMetadata(),
                    executionOptions(), ContributableMatcher.ALL, sourceDescriptor(),
                    targetDescriptor(file));
        } finally {
            StandardServiceRegistryBuilder.destroy(registry);
        }

        String sql = Files.readString(file, StandardCharsets.UTF_8).toLowerCase();
        assertThat(sql).contains("crawler_catalog", "crawler_resource", "crawler_image",
                "crawler_resource_image", "crawler_report");
        // the indexes are part of the schema, not an afterthought: a catalog page reads by
        // catalog and version on every request
        assertThat(sql).contains("idx_resource_catalog_ver");
        prependHeader(file, name, dialect);
    }

    private ExecutionOptions executionOptions() {
        return new ExecutionOptions() {

            @Override
            public Map<String, Object> getConfigurationValues() {
                // read here rather than only on the registry: this is what the creator consults,
                // and without it every table comes out as one very long line
                return Map.of(AvailableSettings.FORMAT_SQL, "true");
            }

            @Override
            public boolean shouldManageNamespaces() {
                return false;
            }

            @Override
            public ExceptionHandler getExceptionHandler() {
                return exception -> {
                    throw exception;
                };
            }
        };
    }

    /** Straight to the file, and nowhere near a database. */
    private TargetDescriptor targetDescriptor(Path file) {
        return new TargetDescriptor() {

            @Override
            public EnumSet<TargetType> getTargetTypes() {
                return EnumSet.of(TargetType.SCRIPT);
            }

            @Override
            public ScriptTargetOutput getScriptTargetOutput() {
                return new ScriptTargetOutputToFile(file.toFile(), StandardCharsets.UTF_8.name());
            }
        };
    }

    private SourceDescriptor sourceDescriptor() {
        return new SourceDescriptor() {

            @Override
            public SourceType getSourceType() {
                return SourceType.METADATA;
            }

            @Override
            public org.hibernate.tool.schema.spi.ScriptSourceInput getScriptSourceInput() {
                return null;
            }
        };
    }

    /** So somebody opening the file knows what wrote it and what to do with it. */
    private void prependHeader(Path file, String name, String dialect) throws IOException {
        String body = Files.readString(file, StandardCharsets.UTF_8).trim();
        String header = """
                -- Greenfinger 2.0 schema for %s.
                --
                -- Generated by SchemaScriptsTest from the entities; do not edit by hand -- run the
                -- test instead, or the next run will overwrite whatever was typed here.
                --
                -- Dialect: %s
                --
                -- Run this once against an empty database, then start the nodes with
                -- GF_DB_DDL=validate so that Hibernate checks the schema rather than changing it.
                -- The default, update, only ever adds: a column whose type changed is left alone,
                -- a dropped one stays, and two nodes starting together race to create the same
                -- table.

                """.formatted(name, dialect);
        Files.writeString(file, header + body + "\n", StandardCharsets.UTF_8);
    }
}
