server:
  port: 6120
spring:
  application:
    name: greenfinger-console-service
  profiles:
    active: local
  scheduler:
    run-mode: variable
  redis:
    lettuce:
      pool:
        max-active: 20
        max-idle: 2
        min-idle: 1
        max-wait: 10000
  datasource:
    hikari:
      connection-timeout: 2000
      minimum-idle: 5
      maximum-pool-size: 20
      idle-timeout: 200000
      auto-commit: true
      max-lifetime: 1800000
      connection-test-query: select 1
    
doodler:
  cloud:
    sibling:
      quick-start: false 
    
management:
  server:
    port: 6120
  security:
    enabled: false
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: '*'
      base-path: /monitor
  jmx:
    exposure:
      include: '*'
  metrics:
    tags:
      application: '${spring.application.name}'


    
