spring:
  redis:
    database: 0
    host: localhost
    port: 6379
    password: 123456
  elasticsearch:
    rest:
      uris: http://192.168.159.1:9200
      connection-timeout: 5000
      read-timeout: 60000
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/test?characterEncoding=utf8&allowMultiQueries=true&useSSL=false&stringtype=unspecified
    username: fengy
    password: 123456

doodler:
  transmitter:
    nio:
      selection: netty
      server:
        bindHostName: 192.168.159.1